<?xml version="1.0"?>
<robot name="smartcar" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- inertial parameter macros -->

<xacro:macro name="smartcar_wheel" params="prefix front:=false">
    <link name="${prefix}_wheel">  
        <visual>  
            <geometry>  
                <!-- cylinder radius="${wheel_radius}" length="${wheel_length}"/ -->   
		<xacro:if value="${front}">
			<cylinder radius="${wheel_radius}" length="${wheel_length_front}"/> 
		</xacro:if>
		<xacro:unless value="${front}">
			<cylinder radius="${wheel_radius}" length="${wheel_length_rear}"/> 
		</xacro:unless>
            </geometry>  

            <material name="black">  
                <color rgba="0 0 0 1"/>  
            </material>  
        </visual>
    	<collision>
      	  <geometry>
        	<!--cylinder radius="${wheel_radius}" length="${wheel_length}"/ -->
		<xacro:if value="${front}">
			<cylinder radius="${wheel_radius}" length="${wheel_length_front}"/> 
		</xacro:if>
		<xacro:unless value="${front}">
			<cylinder radius="${wheel_radius}" length="${wheel_length_rear}"/> 
		</xacro:unless>
     	  </geometry>
    	</collision>
    	<inertial>
	  <mass value="0.34055" />
	  <inertia ixx="0.00026046" ixy="0"          ixz="0"
		                    iyy="0.00026046" iyz="0"
		                                     izz="0.00041226" />
    	</inertial>
    </link>  
</xacro:macro>

<xacro:macro name="steering_hinge_inertial_params">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <mass value="0.100" />
  <inertia ixx="4E-06" ixy="0"           ixz="0"
                            iyy="4E-06"  iyz="0"
                                              izz="4E-06" />
</xacro:macro>



<xacro:macro name="left_steering_hinge_geometry">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <geometry>
    <mesh filename="package://mushr_description/meshes/left_steering_hinge.STL" />
  </geometry>
</xacro:macro>

<xacro:macro name="right_steering_hinge_geometry">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <geometry>
    <mesh filename="package://mushr_description/meshes/right_steering_hinge.STL" />
  </geometry>
</xacro:macro>


<!-- Construct Four Wheel Axle -->
<xacro:macro name="four_wheel_axles">
  <link name="front_right_wheel_axle">
    <visual>
      <geometry>
        <cylinder radius="${wheel_axle_radius}" length="${wheel_axle_length}"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
  </link>
    <gazebo reference="front_right_wheel_axle">
        <material>Gazebo/Red</material>
    </gazebo> 
  <joint name="base_to_front_right_wheel_axle" type="fixed">
    <parent link="base_link"/>
    <child link="front_right_wheel_axle"/>
    <origin rpy="0 ${pi/2} 0" xyz="${(chassis_width - wheel_axle_length * 2)/2 + wheel_axle_length/2} ${wheelbase / 2} 0"/> 
  </joint>


  <link name="front_left_wheel_axle">
    <visual>
      <geometry>
        <cylinder radius="${wheel_axle_radius}" length="${wheel_axle_length}"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
  </link>
    <gazebo reference="front_left_wheel_axle">
        <material>Gazebo/Red</material>
    </gazebo> 
  <joint name="base_to_front_left_wheel_axle" type="fixed">
    <parent link="base_link"/>
    <child link="front_left_wheel_axle"/>
    <origin rpy="0 ${pi/2} 0" xyz="${-(chassis_width - wheel_axle_length * 2)/2 - wheel_axle_length/2} ${wheelbase / 2} 0"/> 
  </joint>

  <link name="rear_right_wheel_axle">
    <visual>
      <geometry>
        <cylinder radius="${wheel_axle_radius}" length="${wheel_axle_length}"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
  </link>
    <gazebo reference="rear_right_wheel_axle">
        <material>Gazebo/Red</material>
    </gazebo> 
  <joint name="base_to_rear_right_wheel_axle" type="fixed">
    <parent link="base_link"/>
    <child link="rear_right_wheel_axle"/>
    <origin rpy="0 ${pi/2} 0" xyz="${(chassis_width - wheel_axle_length * 2)/2 + wheel_axle_length/2} ${-wheelbase / 2} 0"/> 
  </joint>

  <link name="rear_left_wheel_axle">
    <visual>
      <geometry>
        <cylinder radius="${wheel_axle_radius}" length="${wheel_axle_length}"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
  </link>
    <gazebo reference="rear_left_wheel_axle">
        <material>Gazebo/Red</material>
    </gazebo> 
  <joint name="base_to_rear_left_wheel_axle" type="fixed">
    <parent link="base_link"/>
    <child link="rear_left_wheel_axle"/>
    <origin rpy="0 ${pi/2} 0" xyz="${-(chassis_width - wheel_axle_length * 2)/2 - wheel_axle_length/2} ${-wheelbase / 2} 0"/> 
  </joint>
</xacro:macro>


<!-- transmission macros -->

<xacro:macro name="wheel_transmission" params="name">
  <transmission name="${name}_transmission" type="SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${name}_throttle">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</xacro:macro>

<xacro:macro name="steering_hinge_transmission" params="name">
  <transmission name="${name}_transmission" type="SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${name}_hinge_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</xacro:macro>

<material name="grey">
  <color rgba="0.2 0.2 0.2 1.0"/>
</material>

</robot>
